apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::838048178673:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-G2S2Q2ZNA7GK\n
    \ username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n
    \ rolearn: arn:aws:iam::838048178673:role/UdacityFlaskDeployCBKubectlRole\n  username:
    build \n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-01T19:10:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5946"
  uid: 74ff9a55-f4eb-4a13-9775-a5938b9193aa
