apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::091879332418:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1SY860K1YFJCL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::091879332418:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-06T22:20:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1675"
  uid: f4b4b697-2917-4001-9881-df0af12929bb
